config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'help' => 'pages#help'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  get 'stats' => 'stats#show'
  get 'sample' => 'stats#sample'
  get 'shared/:user' => 'stats#shared', as: :shared

  get 'stats/topic/:topic' => 'stats#topic', as: :topic
  get 'sample/topic/:topic' => 'stats#sample_topic', as: :sample_topic
  get 'shared/:user/topic/:topic' => 'stats#shared_topic', as: :shared_topic

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'forgot' => 'password_resets#new'
  post 'forgot' => 'password_resets#create'
  get 'reset/:id' => 'password_resets#edit', as: :reset
  patch 'reset/:id' => 'password_resets#update'

  get 'game' => 'games#game', as: :game
  delete 'delete/:game_id' => 'games#destroy', as: :delete

  get 'backup/:backup_id/download' => 'backups#download'

  # Allow only Ajax requests to the following routes:
  constraints(->(req) { req.xhr? }) do
    get 'json/:game_id' => 'games#json', as: :json
    post 'save' => 'games#save', as: :save
    patch 'redate' => 'games#redate', as: :redate
    get 'check/:final_id' => 'games#check', as: :check

    patch 'filters' => 'users#update_user_filters'
    patch 'sharing' => 'users#update_sharing_status'

    get 'stats/games' => 'stats#games', as: :games
    get 'sample/games' => 'stats#sample_games', as: :sample_games
    get 'shared/:user/games' => 'stats#shared_games', as: :shared_games

    get 'backup' => 'backups#new'
    get 'backup/:backup_id' => 'backups#status'
    post 'restore' => 'backups#restore'
    get 'restore/:restore_id' => 'backups#restore_progress'
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :find_user,        only: %i[edit update]
  before_action :valid_user,       only: %i[edit update]
  before_action :check_expiration, only: %i[edit update]
  before_action :password_present, only: %i[update]

  def new; end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
    end
    flash[:info] = 'If this address exists in the database, an email with ' \
                   'password reset instructions will be sent in the next ' \
                   'minute or two. Thanks for your patience.'
    redirect_to root_url
  end

  def edit; end

  def update
    if @user.update(user_params)
      log_in @user
      # rubocop:disable SkipsModelValidations
      @user.update_attribute(:reset_digest, nil)
      # rubocop:enable SkipsModelValidations
      flash[:success] = 'Password has been reset.'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # Before filters

  def find_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
    return 'OK' if @user&.authenticated?(:reset, params[:id])
    redirect_to root_url
  end

  def check_expiration
    return 'OK' unless @user.password_reset_expired?
    flash[:danger] = 'Password reset has expired.'
    redirect_to forgot_url
  end

  def password_present
    return 'OK' unless params[:user][:password].empty?
    @user.errors.add(:password, "can't be empty")
    render 'edit'
  end
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>

<br />
<h1>Reset password</h1>
<br />

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@user, url: reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, 'Choose a new password' %>
      <%= f.password_field :password, class: 'form-control', tabindex: 1 %>

      <%= f.label :password_confirmation, 'Confirm new password' %>
      <%= f.password_field :password_confirmation, class: 'form-control',
                                                   tabindex: 2 %>
      <br />

      <%= f.submit "Update password", class: 'btn btn-primary submit-button',
                                      data: { disable_with: 'Updating...' },
                                      tabindex: 3 %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, 'Forgot password') %>
<% provide(:tags, "description: If you've forgotten your J! Scorer password, you can request a new one here. Instructions will be emailed to you.".html_safe) %>

<br />
<h1>Forgot password</h1>
<br />

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(:password_reset, url: forgot_path) do |f| %>
      <%= f.label :email, 'Email address' %>
      <%= f.email_field :email, class: 'form-control',
                                spellcheck: false,
                                tabindex: 1 %>
      <br />

      <%= f.submit 'Submit', class: 'btn btn-primary submit-button',
                             data: { disable_with: 'Submitting...' },
                             tabindex: 2 %>
    <% end %>
  </div>
</div>