config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'help' => 'pages#help'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  get 'stats' => 'stats#show'
  get 'sample' => 'stats#sample'
  get 'shared/:user' => 'stats#shared', as: :shared

  get 'stats/topic/:topic' => 'stats#topic', as: :topic
  get 'sample/topic/:topic' => 'stats#sample_topic', as: :sample_topic
  get 'shared/:user/topic/:topic' => 'stats#shared_topic', as: :shared_topic

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'forgot' => 'password_resets#new'
  post 'forgot' => 'password_resets#create'
  get 'reset/:id' => 'password_resets#edit', as: :reset
  patch 'reset/:id' => 'password_resets#update'

  get 'game' => 'games#game', as: :game
  delete 'delete/:game_id' => 'games#destroy', as: :delete

  get 'backup/:backup_id/download' => 'backups#download'

  # Allow only Ajax requests to the following routes:
  constraints(->(req) { req.xhr? }) do
    get 'json/:game_id' => 'games#json', as: :json
    post 'save' => 'games#save', as: :save
    patch 'redate' => 'games#redate', as: :redate
    get 'check/:final_id' => 'games#check', as: :check

    patch 'filters' => 'users#update_user_filters'
    patch 'sharing' => 'users#update_sharing_status'

    get 'stats/games' => 'stats#games', as: :games
    get 'sample/games' => 'stats#sample_games', as: :sample_games
    get 'shared/:user/games' => 'stats#shared_games', as: :shared_games

    get 'backup' => 'backups#new'
    get 'backup/:backup_id' => 'backups#status'
    post 'restore' => 'backups#restore'
    get 'restore/:restore_id' => 'backups#restore_progress'
  end
end

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:tags, 'description: Who is behind this madness? Meet the developer, Steve McClellan. Care to contribute? Be my guest! Link within.') %>

<div id="about-page">
  <div class="col-xs-10 col-xs-offset-1 booyah-box">
    <h1>About</h1>
    <br />

    <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      <p>
      The J! Scorer was built by <a class="nowrap" target="_blank" href="https://github.com/steve-mcclellan">Steve</a> <a class="nowrap" target="_blank" href="https://linkedin.com/in/steve-mcclellan">McClellan</a>, because he wanted something like it to exist.
      </p>
      <br />
      <p>
      This is an open-source project - if you'd like to contribute, or just see what's going on under the hood, hop on over to <a target="_blank" href="https://github.com/steve-mcclellan/j-scorer">the J! Scorer GitHub repo</a>.
      </p>
      <br />
      <br />

      <div class="col-xs-12 col-sm-4">
        <%= image_tag 'steve.jpg', class: 'img-responsive' %>
      </div>

      <div class="visible-xs-block">
        &nbsp;<hr />
      </div>

      <div class="col-xs-12 col-sm-7 col-sm-offset-1">
        <h2>Steve McClellan</h2>
        <br />
        <p>
        Steve McClellan (seen here in his appearance on <i>J!</i>'s sister show) is a software developer and game show aficionado. In previous lives, he has been a poker dealer and high school sports official. He can be reached at <a class="nowrap" href="mailto:<%= ENV['SUPPORT_ADDRESS'] %>"><%= ENV['SUPPORT_ADDRESS'] %></a>.
        </p>
      </div>
    </div>
  </div> <!-- booyah-box -->
</div> <!-- about-page -->

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<% provide(:tags, 'description: What the heck is a J! Scorer? A Coryat score? Why would I want to use them? How can I? Answers within.') %>

<div id="help-page">
  <%# <div class="col-xs-10 col-xs-offset-1 j-box"> %>
    <%# <p> %>
    <%# Welcome! The J! Scorer is still fairly young - any feedback is greatly appreciated. Have an idea for how something could be easier to use, or look better? Want to see a specific stat? Send any and all thoughts to <a class="nowrap" href="mailto:<%= ENV['SUPPORT_ADDRESS'] % >"><%= ENV['SUPPORT_ADDRESS'] % ></a>. %>
    <%# </p> %>
  <%# </div> %>

  <div class="col-xs-10 col-xs-offset-1 booyah-box">
    <h2>J! Scorer - What, Why, and How</h2>
    <br />
    <p>
    The J! Scorer makes it easy for prospective <em>Jeopardy!</em> contestants to play along with the show and keep track of their training progress.
    </p>
    <br />
    <div style="background-color: yellow; border: 1px solid black; padding-left: 10px; padding-right: 10px;">
        <br />
        <h2>NOTE ON PRIME-TIME CELEBRITY GAMES</h2>
        <br />
        <p>
          It would require a huge amount of effort to properly handle the extra round present in the hour-long celebrity episodes. As long as it's only celebrity games, I will not be expending that effort, and these games will be officially unsupported. (If you find this unacceptable, feel free to <a href="https://github.com/steve-mcclellan/j-scorer">make the changes yourself.</a>)
        </p>
        <br />
        <p>
          I strongly recommend skipping play-along with these games. But if you really, <strong>really</strong> want to play along with them, note:
        </p>
        <ol>
          <li>If you choose the "Celebrity" play type with an appropriate show date (i.e., 2022-09-25 or later), it will give you the correct values for the first two rounds.</li>
          <li>There is a new "Triple round" play type that will give you $300-$1500 values.</li>
          <li>There is no way to join those into a single game, and no way to properly handle stats for three Daily Doubles in a round.</li>
          <li>If you save these games, the stats page will adjust all displayed values to the $200-$2000 values that the syndicated show currently uses.</li>
        </ol>
        <br />
        <p>
          Again, these games are not supported, and I strongly recommend skipping play-along with them, but if there's anything <strong>simple</strong> that you'd like to suggest, drop me a line at the address below.
        </p>
        <br />
    </div>
    <br />
    <p>
    Both guests and registered users can use the J! Scorer to calculate their <a class="nowrap" href="http://www.pisspoor.com/jep.html" target="_blank">Coryat score</a> while playing along with the show in real time. Registered users can also save their games and track their stats over time. (See an interactive sample stats page <%= link_to 'here', sample_path %>.)
    </p>
    <br />
    <p>
    The <%= link_to 'game page', game_path, class: "nowrap" %> is where the action is.
    </p>
    <br />
    <%= image_tag "game_page.png", class: 'img-responsive center-block' %>
    <br />
    <p>
    As on the show, the blue boxes at the top of the board are where the category names go. As the categories are revealed on the show, type in a bit of the name - enough to find the proper column when a clue is selected. (This area is for your reference only, and has no effect on any stats.)
    </p>
    <br />
    <p>
    When a contestant selects a clue, click on (or touch) the appropriate box. This will bring up an overlay with several buttons. Click on <strong>Right</strong> or <strong>Wrong</strong> as appropriate for your response, or <strong>Pass</strong> if you chose to <a class="nowrap" href="http://j-archive.com/help.php#stayclam" target="_blank">STAY CLAM</a>. When a Daily Double is uncovered, tick the <strong>DD</strong> checkbox. The <strong>NR</strong> button is for any clues that go unrevealed.
    </p>
    <br />
    <%= image_tag "clue_overlay.png", class: 'img-responsive center-block' %>
    <br />
    <p>
    If you plan on saving your game, at the conclusion of each round, you can enter zero or more custom <strong>topics</strong> for each category in the white box between the category name and the clue boxes. (Separate multiple topics with commas.) After your game has been saved, your results from that category will be added to your totals for each topic on the <%= link_to 'stats page', stats_path, class: "nowrap" %>.
    </p>
    <br />
    <p>
    (For example, if the category is BEFORE &amp; AFTER, you might assign topics <em>Wordplay, General Knowledge</em>. If the category is SHAKESPEARE, your topics might be <em>Entertainment, Highbrow, Theatre, Shakespeare</em>. For best results, use whatever comes naturally to you; consistency is the key to good, useful stats.)
    </p>
    <br />
    <%= image_tag "topic_and_round_links.png", class: 'img-responsive center-block' %>
    <br />
    <p>
    Navigate between rounds with the links below the scoreboard.
    </p>
    <br />
    <p>
    For the Final clue, the category and topic areas work as before. Use the large <strong>Right</strong> or <strong>Wrong</strong> button to record your result. A check mark or an X will appear next to your score, as appropriate.
    </p>
    <br />
    <%= image_tag "final_overlay.png", class: 'img-responsive center-block' %>
    <br />
    <p>
    At the bottom of the Final area, there are places to enter the on-air contestants' results. (Use their positions entering Final, <i>i.e.</i>, just enter the results left-to-right, as third place is revealed first on the show.) This will enable you to view your Final stats broken down by contestant results, which can come in handy if you find yourself facing, say, <a class="nowrap" href="http://j-archive.com/help.php#strattonsdilemma" target="_blank">Stratton's Dilemma</a>.
    </p>
    <br />
    <p>
    To save your game, make sure that the show date, date and time played, play type, and rerun status are correct, then click the <strong>Save game</strong> link. When the game is successfully saved, the text of the link will change accordingly.
    </p>
    <br />
    <p>
    (Note: Your most-recently-displayed game is saved to a cookie in your browser. This enables you to visit other pages, like the login or signup page, and still have your game waiting for you when you return. To start a new game, click the <strong>New game</strong> link below the save area.)
    </p>
    <br />
    <p>
    Happy playing! If you have any questions that aren't answered here (including the notes below and tacky yellow box above), please email <a class="nowrap" href="mailto:<%= ENV['SUPPORT_ADDRESS'] %>"><%= ENV['SUPPORT_ADDRESS'] %></a>.
    </p>
    <br />
    <p>
    <strong>A note on browsers:</strong> The J! Scorer is developed primarily for recent versions of Firefox, with regular checks that it works reasonably well in recent versions of Chromium/Google Chrome. Support for other browsers is not planned at this time.
    </p>
    <br />
    <p>
    <strong>A note on mobile devices:</strong> In designing the J! Scorer, my decisions are aimed at maximum usability on laptops and desktops. Smaller-screened devices can work, but will likely need to be rotated so the screen is wider than it is tall.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<% provide(:tags, 'description: A full-featured Jeopardy! scorekeeper and stat tracker for contestants-in-training.; world peace: Formerly known as Ron Artest') %>

<div id="home-container">
  <% if logged_in? %>
    <p>Welcome back, <%= current_user.email %>!</p>
    <div><%= link_to 'Enter a Game', game_path, class: 'btn btn-primary' %></div>
    <div><%= link_to 'View My Stats', stats_path, class: 'btn btn-primary' %></div>
    <div><%= link_to 'Help', help_path, class: 'btn btn-primary' %></div>
  <% else %>
    <p>Welcome, Guest!</p>
    <div><%= link_to 'What is This?', help_path, class: 'btn btn-primary' %></div>
    <div><%= link_to 'Enter a Game', game_path, class: 'btn btn-primary' %></div>
    <div>
      <div class="soft-sell">
        <p>
          See a <%= link_to "sample stats page", sample_path, class: "nowrap" %>.
        </p>
        <p>
          To track your own stats,
        </p>
        <p>
          <%= link_to 'log in', login_path, class: "nowrap" %>
          or
          <%= link_to 'sign up', signup_path, class: "nowrap" %>.
        </p>
      </div>
    </div>
  <% end %>
</div>