config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'help' => 'pages#help'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  get 'stats' => 'stats#show'
  get 'sample' => 'stats#sample'
  get 'shared/:user' => 'stats#shared', as: :shared

  get 'stats/topic/:topic' => 'stats#topic', as: :topic
  get 'sample/topic/:topic' => 'stats#sample_topic', as: :sample_topic
  get 'shared/:user/topic/:topic' => 'stats#shared_topic', as: :shared_topic

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'forgot' => 'password_resets#new'
  post 'forgot' => 'password_resets#create'
  get 'reset/:id' => 'password_resets#edit', as: :reset
  patch 'reset/:id' => 'password_resets#update'

  get 'game' => 'games#game', as: :game
  delete 'delete/:game_id' => 'games#destroy', as: :delete

  get 'backup/:backup_id/download' => 'backups#download'

  # Allow only Ajax requests to the following routes:
  constraints(->(req) { req.xhr? }) do
    get 'json/:game_id' => 'games#json', as: :json
    post 'save' => 'games#save', as: :save
    patch 'redate' => 'games#redate', as: :redate
    get 'check/:final_id' => 'games#check', as: :check

    patch 'filters' => 'users#update_user_filters'
    patch 'sharing' => 'users#update_sharing_status'

    get 'stats/games' => 'stats#games', as: :games
    get 'sample/games' => 'stats#sample_games', as: :sample_games
    get 'shared/:user/games' => 'stats#shared_games', as: :shared_games

    get 'backup' => 'backups#new'
    get 'backup/:backup_id' => 'backups#status'
    post 'restore' => 'backups#restore'
    get 'restore/:restore_id' => 'backups#restore_progress'
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  include Pagy::Backend

  before_action :logged_in_user, only: %i[show topic]
  before_action :find_shared_stats_user, only: %i[shared shared_topic shared_games]
  before_action :set_sample_user, only: %i[sample sample_topic sample_games]

  def show
    @user = current_user
    @user_name = @user.email

    set_play_types
    set_filters
    set_stats_vars
  end

  def sample
    @sample = true

    set_play_types
    set_filters
    set_stats_vars
    render 'show'
  end

  def shared
    @shared = true

    set_play_types
    set_filters
    set_stats_vars
    render 'show'
  end

  def games
    @user = current_user
    @user_name = @user.email

    set_play_types
    set_filters
    set_games('stats')

    render layout: false
  end

  def sample_games
    @sample = true

    set_play_types
    set_filters
    set_games('sample')

    render 'games', layout: false
  end

  def shared_games
    @shared = true

    set_play_types
    set_filters
    set_games('shared')

    render 'games', layout: false
  end

  def topic
    @user = current_user
    @user_name = @user.email
    find_and_render_topic
  end

  def sample_topic
    @sample = true
    find_and_render_topic
  end

  def shared_topic
    unless @user.share_detailed_stats
      render plain: 'Detailed stats not available for this user',
             status: :forbidden
      return
    end
    @shared = true
    find_and_render_topic
  end

  private

  def find_and_render_topic
    @topic = Topic.find_by('LOWER(name) = ? AND user_id = ?',
                           params[:topic].downcase, @user.id)
    render plain: 'Topic not found', status: :not_found and return if @topic.nil?

    set_play_types
    set_filters
    set_topics
    render 'topic'
  end

  def set_sample_user
    @user = ENV['SAMPLE_USER'] ? User.find(ENV['SAMPLE_USER']) : User.first
    @user_name = ENV['SAMPLE_USER_NAME'] || @user.email
  end

  def find_shared_stats_user
    @user = User.find_by('LOWER(shared_stats_name) = ?', params[:user].downcase)
    render plain: 'User not found', status: :not_found and return if @user.nil?
    @user_name = @user.shared_stats_name
  end

  def set_play_types
    @play_types = if params[:play_types] == 'all'
                    PLAY_TYPES.keys
                  elsif params[:play_types]
                    params[:play_types].split(',')
                  elsif !(@shared || @sample)
                    current_user.play_types
                  else
                    ['regular']
                  end.select { |type| VALID_TYPE_INPUTS.include?(type) }
  end

  def set_filters
    @filters = if filters_from_params.values.any?
                 filters_from_params
               elsif @shared || @sample
                 filters_from_params.update(rerun_status: 'first')
               else
                 current_user.filter_preferences
               end
  end

  def filters_from_params
    return @ffp if @ffp
    @ffp = Hash[FILTER_FIELDS.map { |field| [field, params[field]] }]
    booleanize_verbs
    sanitize_dates
    @ffp
  end

  def booleanize_verbs
    %i[show_date_reverse date_played_reverse].each do |field|
      next if @ffp[field].blank?
      @ffp[field] = (@ffp[field] == 'true')
    end
  end

  def sanitize_dates
    %i[show_date_beginning show_date_from show_date_to
       date_played_beginning date_played_from date_played_to].each do |field|
      next if @ffp[field].blank?
      begin
        @ffp[field] = Date.parse(@ffp[field]).strftime('%F')
      rescue ArgumentError
        @ffp[field] = nil
      end
    end
  end

  def set_stats_vars
    filter_sql = User.filter_sql(@filters)
    @summary = @user.multi_game_summary(@play_types, filter_sql)
    @percentile_stats = @user.percentile_report(@play_types, filter_sql)
    @stats_by_topic = @user.topics_summary(@play_types, filter_sql)
    @stats_by_row = @user.results_by_row(@play_types, filter_sql)
    @final_stats = @user.final_stats(@play_types, filter_sql)
    @play_type_summary = @user.play_type_summary(filter_sql)
  end

  def set_topics
    filter_sql = User.filter_sql(@filters)
    @categories = @user.topic_details(@topic, @play_types, filter_sql)
  end

  def set_games(stats_page_type)
    dataset = @user.games_for(params, @filters, @play_types)
    page_link_html = "class=\"page-link\" data-pagetype=\"#{stats_page_type}\""

    @pagy, @games = pagy(dataset, link_extra: page_link_html)
  end
end

app/helpers/stats_helper.rb
module StatsHelper
  include Pagy::Frontend

  def pagy_url_for(_pagy, page)
    "#{stats_url}#games_#{page}"
  end
end

app/views/stats/_by_row.html.erb
<div id="by-row">
  <% [:round_one, :round_two].each_with_index do |round, round_index| %>
    <div class="round-by-row">
      <% 1.upto(5) do |row_number| %>
        <div class="by-row-row">
          <div class="by-row-value-box">
            $<%= CURRENT_TOP_ROW_VALUES[round_index] * row_number %>:
          </div>
          <div class="by-row-regular-box"
               style="background-color: <%= stats[round][row_number]['regular_color'] %>;">
            <div class="counting-stats three-liner">
              <div>
                <span class="check"><abbr title="Clues right" rel="tooltip">&#x2713;</abbr></span>
                <%= stats[round][row_number]['right'] %>
              </div>
              <div>
                <span class="ecks"><abbr title="Clues wrong" rel="tooltip">&#x2718;</abbr></span>
                <%= stats[round][row_number]['wrong'] %>
              </div>
              <div>
                <span class="dot"><abbr title="Clues passed" rel="tooltip">&#x2022;</abbr></span>
                <%= stats[round][row_number]['pass'] %>
              </div>
            </div> <!-- counting-stats -->
            <div class="rate-stats three-liner">
              <div><abbr title="Your score as a percentage of the total possible. For a single row, this is equal to ((clues right) - (clues wrong)) / (total clues revealed)" rel="tooltip">Efficiency</abbr>:</div>
              <div><%= stats[round][row_number]['eff_num'] %>/<%= stats[round][row_number]['eff_den'] %></div>
              <% unless (eff = stats[round][row_number]['efficiency']).nil? %>
                <div>(<%= number_to_percentage(eff * 100, precision: 1) %>)</div>
              <% end %>
            </div>
          </div> <!-- by-row-regular-box -->
          <div class="by-row-dd-box three-liner"
               style="background-color: <%= stats[round][row_number]['dd_color'] %>;">
            <div><abbr title="Daily Doubles. These are not included in the main stats" rel="tooltip">DDs</abbr>:</div>
            <div><%= (ddr = stats[round][row_number]['dd_right']) %>/<%= stats[round][row_number]['dd_wrong'] + ddr %></div>
            <% unless (dd_eff = stats[round][row_number]['dd_eff']).nil? %>
              <div>(<%= number_to_percentage(dd_eff * 100, precision: 1) %>)</div>
            <% end %>
          </div> <!-- by-row-dd-box -->
        </div> <!-- by-row-row -->
      <% end %> <!-- each row number -->
    </div> <!-- round-by-row -->
  <% end %> <!-- each round -->
</div>

app/views/stats/_filter_update_button.html.erb
<div class="text-center">
  <% if @shared %>
    <button type="button" class="update-filters update-shared-filters" data-username= "<%= url_encode(@user.shared_stats_name) %>">
  <% elsif @sample %>
    <button type="button" class="update-filters update-sample-filters">
  <% else %>
    <button type="button" class="update-filters update-user-filters">
  <% end %>
      Apply all filters
    </button>
</div>

app/views/stats/_options.html.erb
<div id="options" class="col-xs-12">
  <br />
  <div class="clearfix">
    <h2>Stat Sharing</h2>
    <div id="stat-sharing-section">
      <%= render 'options_sharing' %>
    </div> <!-- stat-sharing-section -->
  </div> <!-- Stat Sharing clearfix -->
  <br />
  <hr />
  <br />
  <div class="clearfix">
    <h2>Backup/Restore</h2>
    <div class="isolated-sentence">
      (<a href="#" data-toggle="modal" data-target="#why-backup-modal">Why back up?</a>)
    </div>
    <div id="backup-sentence" class="isolated-sentence">
      Download a backup file of your games by clicking
      <% if current_user?(@user) %>
        <a href="#" id="backup-link">here</a>.
      <% else %>
        <span class="disabled">here</span>.
      <% end %>
    </div>
    <a href="#" id="invisible-download-link" style="display: none;"></a>
    <div class="isolated-sentence">
      Add games from a previously-generated backup file
      <% if current_user?(@user) %>
        <a href="#" data-toggle="modal" data-target="#restore-modal">here</a>.
      <% else %>
        <span class="disabled">here</span>.
      <% end %>
    </div>
  </div> <!-- Back up/Restore clearfix -->
  <br />

  <!-- above: main tab content; below: modals -->

  <!-- Stat-sharing modal -->
  <div id="sharing-modal" class="modal fade" tabindex="-1" role="dialog"
       aria-labelledby="sharing-modal-label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h3 class="modal-title" id="sharing-modal-label">
            Sharing settings
          </h3>
        </div>

        <%= form_with(model: @user,
                      url: sharing_path,
                      method: 'patch',
                      id: 'sharing-form') do |f| %>
          <div class="modal-body">
            <div class="row">
              <div class="col-xs-12 col-compact">
                <div class="form-group">
                  <p>
                    To share your stats, enter a public username. For private stats, leave this box blank.
                  </p>
                  <div class="spacer">&nbsp;</div>
                  <div id="sharing-settings-error"></div>
                  <%= f.text_field(:shared_stats_name, spellcheck: 'false') %>
                  <%= f.check_box(:share_detailed_stats) %>
                  <%= f.label(:share_detailed_stats, 'Share detailed stats?') %>
                  <p class="sidebar">
                    COMING SOON: You'll be able to drill down into a topic or a game and see clue-by-clue results. Check this box to make these detailed stats shareable. Leave it unchecked to share summary stats only.
                  </p>
                </div> <!-- form-group -->
              </div> <!-- col-xs-12 -->
            </div> <!-- row -->
          </div> <!-- modal-body -->

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              Close
            </button>
            <%= f.submit('Save settings',
                         id: 'sharing-submit-button',
                         class: 'btn btn-primary',
                         data: { disable_with: 'Saving...' }) %>
          </div>
        <% end %>

      </div> <!-- modal-content -->
    </div> <!-- modal-dialog -->
  </div> <!-- Stat-sharing modal -->

  <!-- Why-backup modal -->
  <div id="why-backup-modal" class="modal fade" tabindex="-1" role="dialog"
       aria-labelledby="why-backup-modal-label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title" id="why-backup-modal-label">
              Why back up?
            </h3>
          </div>

          <div class="modal-body">
            <p>
              As the J! Scorer is <a href="https://github.com/steve-mcclellan/j-scorer" target="_blank">open source</a>, anyone is free to create their own instance of it for any reason. (Someone might want their own customized version, or simply a version where they control everything, including the database.)
            </p>
            <br />
            <p>
              Each instance will have its own separate database, and the only way to move games from one instance to another is through this back-up-and-restore feature.
            </p>
            <br />
            <p>
              It's a good idea to always keep a recent backup file on hand, just in case this instance or its database should vanish unexpectedly.
            </p>
            <br />
            <p>
              I intend to leave this instance up and running for as long as anyone is actively using it. That said, sometimes plans change, sometimes people become unable to execute their plans despite their best efforts, and sometimes service providers lose databases.
            </p>
            <br />
            <p>
              If any of these things happens, anyone who can set up a Ruby on Rails application can create a new J! Scorer instance. Create an account there, add the games from your recent backup file, and continue your training without major interruption.
            </p>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              Close
            </button>
          </div> <!-- modal-footer -->

      </div> <!-- modal-content -->
    </div> <!-- modal-dialog -->
  </div> <!-- why-backup-modal -->

  <!-- Modal for restoring from backup -->
  <div id="restore-modal" class="modal fade" tabindex="-1" role="dialog"
       aria-labelledby="restore-modal-label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <%= form_with(url: restore_path,
                      method: 'post',
                      multipart: true,
                      id: 'restore-form') do %>

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title" id="restore-modal-label">
              Restore from backup
            </h3>
          </div>

          <div class="modal-body">
            <div class="row" id="restore-modal-body">
              <div class="col-xs-12 col-compact">
                <div class="input-group" id="restore-form-group">
                  <label for="file">Backup file (*.jscor):</label>
                  <%= file_field_tag 'backup_file', required: true %>
                </div>
              </div>
              <div id="restore-error-message" class="col-xs-12 col-compact"></div>
              <div id="restore-error-message-spacer" class="col-xs-12 col-compact"></div>
              <div class="col-xs-12 col-compact">
                <strong>Warning:</strong> This will add all of the games in the backup file to your user account. If you're not restarting from scratch, this may result in duplicates.
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              Close
            </button>
            <%= submit_tag('Restore',
                           id: 'restore-submit-button',
                           class: 'btn btn-primary',
                           data: { disable_with: 'Restoring...' }) %>
          </div> <!-- modal-footer -->

        <% end %>
      </div> <!-- modal-content -->
    </div> <!-- modal-dialog -->
  </div> <!-- restore-modal -->
</div> <!-- options tab -->

app/views/stats/_options_sharing.html.erb
<% if @user.shared_stats_name.nil? %>
  <div class="isolated-sentence">
    Your stats are currently visible only to you.
  </div>
<% else %>
  <div class="isolated-sentence">
    <% shared_url = request.base_url + '/shared/' + url_encode(@user.shared_stats_name) %>
    Your <u><%= @user.share_detailed_stats ? 'detailed' : 'summary' %></u> stats are currently viewable at
  </div>
  <div class="isolated-sentence">
    <a href="<%= shared_url %>"><%= shared_url %></a>.
  </div>
<% end %>
<div class="isolated-sentence">
  (If you'd like to change this, click
  <% if current_user?(@user) %>
    <a href="#" data-toggle="modal" data-target="#sharing-modal">here</a>.)
  <% else %>
    <span class="disabled">here</span>.)
  <% end %>
</div>

app/views/stats/_topics.html.erb
<div id="topics">
  <h2>
    Topics for <%= @user_name %>
    <% if stats.size == (user_topics_count = @user.topics.count) %>
      (<%= user_topics_count %>):
    <% else %>
      (<%= stats.size %> of <%= user_topics_count %>):
    <% end %>
  </h2>

  <table id="topicTable" class="tablesorter tablesorter-blue">
    <thead>
      <tr>
        <th>Topic</th>
        <th><abbr title="Not including Finals.">Categories</abbr></th>
        <th><abbr title="Not including Daily Doubles or Finals.">Right</abbr></th>
        <th><abbr title="Not including Daily Doubles or Finals.">Wrong</abbr></th>
        <th><abbr title="Not including Daily Doubles or Finals.">Pass</abbr></th>
        <th>Total Score</th>
        <th>Possible Score</th>
        <th class="end-of-group">
          <abbr title="Total score divided by possible score.">Efficiency</abbr>
          <abbr title="Number of clues in category divided by total
          clues.">Market Share</abbr>
        </th>
        <th>DDs</th>
        <th>Right</th>
        <th>Wrong</th>
        <th class="end-of-group">%</th>
        <th>Finals</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>%</th>
        <th class="end-of-group">
          <abbr title="Get rate of contestants on the show.">On-air %</abbr>
        </th>
      </tr>
    </thead>
    <tbody>
      <!-- Universal Topic -->
      <tr>
        <td>
          <span class="nowrap">--ALL</span>
          <span class="nowrap">CATEGORIES--</span>
        </td>
        <td><%= @summary[:all][:game_count] * 12 %></td>
        <td><%= @summary[:all][:right] %></td>
        <td><%= @summary[:all][:wrong] %></td>
        <td><%= @summary[:all][:pass] %></td>
        <td><%= number_to_currency(@summary[:all][:score], precision: 0) %></td>
        <td><%= number_to_currency(@summary[:all][:possible_score], precision: 0) %></td>
        <td class="end-of-group">
          <%= number_with_precision(@summary[:all][:efficiency], precision: 5) %>
        </td>
        <td><%= @summary[:all][:dds] %></td>
        <td><%= @summary[:all][:dd_right] %></td>
        <td><%= @summary[:all][:dd_wrong] %></td>
        <td class="end-of-group">
          <%= display_percentage_from_rate(@summary[:all][:dd_rate]) %>
        </td>
        <td><%= @summary[:finals][:count] %></td>
        <td><%= @summary[:finals][:right] %></td>
        <td><%= @summary[:finals][:wrong] %></td>
        <td><%= display_percentage_from_rate(@summary[:finals][:rate]) %></td>
        <td class="end-of-group">
          <%= display_percentage_from_rate(@final_stats[:contestants][0][2]) %>
        </td>
      </tr>

      <!-- Individual Topics -->
      <% stats.each do |topic| %>
        <tr>
          <% if @sample %>
            <td><%= link_to topic['topic_name'], sample_topic_path(topic['topic_name'], request.query_parameters), target: '_blank' %></td>
          <% elsif @shared && @user.share_detailed_stats %>
            <td><%= link_to topic['topic_name'], shared_topic_path(@user.shared_stats_name, topic['topic_name'], request.query_parameters), target: '_blank' %></td>
          <% elsif @shared %>
            <td><%= topic['topic_name'] %></td>
          <% else %>
            <td><%= link_to topic['topic_name'], topic_path(topic['topic_name'], request.query_parameters), target: '_blank' %></td>
          <% end %>
          <td><%= topic['sixths_count'] %></td>
          <td><%= topic['right'] %></td>
          <td><%= topic['wrong'] %></td>
          <td><%= topic['pass'] %></td>
          <td><%= number_to_currency(topic['score'], precision: 0) %></td>
          <td><%= number_to_currency(topic['possible_score'], precision: 0) %></td>
          <td class="end-of-group">
            <%= number_with_precision(topic['efficiency'], precision: 5) %>
          </td>
          <td><%= topic['dds'] %></td>
          <td><%= topic['dd_right'] %></td>
          <td><%= topic['dd_wrong'] %></td>
          <td class="end-of-group">
            <%= display_percentage_from_rate(topic['dd_rate']) %>
          </td>
          <td><%= topic['finals_count'] %></td>
          <td><%= topic['finals_right'] %></td>
          <td><%= topic['finals_wrong'] %></td>
          <td><%= display_percentage_from_rate(topic['final_rate']) %></td>
          <td class="end-of-group">
            <%= display_percentage_from_rate(topic['final_onair_rate']) %>
            <!--<%= topic['final_onair_right'] %>/<%= topic['final_onair_den'] %>-->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div id="topics-notes">
    <p id="notes-title">Notes:</p>
    <p><strong>Categories</strong> counts do not include Finals.</p>
    <p><strong>Right</strong>, <strong>Wrong</strong>, and <strong>Pass</strong>
    totals do not include Daily Doubles or Finals.</p>
    <p><strong>Efficiency</strong> is total score divided by possible score.</p>
    <p><strong>On-air %</strong> is the get rate of the contestants on the show for Finals with this topic.</p>
  </div>
</div>

app/views/stats/games.html.erb
<table id="gameTable" class="tablesorter tablesorter-blue">
  <thead>
  <tr>
    <th id="played-at-col" data-abbr="pa">Played at</th>
    <th id="rerun-col" data-abbr="rr">Rerun?</th>
    <th id="show-date-col" data-abbr="sd">Show date</th>
    <th id="play-type-col" data-abbr="pt">Play type</th>
    <th id="coryat-col" data-abbr="cs">Coryat score</th>
    <th id="round-one-col" data-abbr="ro">Round one</th>
    <th id="round-two-col" data-abbr="rt">Round two</th>
    <th id="att-col" data-abbr="at">
      <abbr title="Clues right + Clues wrong (not including Daily Doubles or Final)">Attempts</abbr>
    </th>
    <th id="cor-col" data-abbr="co">
      <abbr title="Clues right (including Daily Doubles but not Final)">Correct</abbr>
    </th>
    <th id="inc-col" data-abbr="in">
      <abbr title="Clues wrong (including Daily Doubles but not Final)">Incorrect</abbr>
    </th>
    <th id="cor-pct-col" data-abbr="cp">
      <abbr title="Clues right / Clues attempted (including Daily Doubles but not Final)">Correct %</abbr>
    </th>
    <th id="dds-right-col" data-abbr="dr">DDs right</th>
    <th id="dds-wrong-col" data-abbr="dw">DDs wrong</th>
    <th id="final-col" data-abbr="fi">Final</th>
    <th colspan=2>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @games.each do |game| %>
    <tr class="<%= game.play_type %>">
      <td><%= game.date_played.in_time_zone.strftime("%Y-%m-%d %I:%M %P") if game.date_played.year > 0 %></td>
      <td><%= game.rerun ? '✓' : '-' %></td>
      <td><%= game.show_date %></td>
      <td><%= PLAY_TYPES[game.play_type] %></td>
      <% if game.round_one_score.present? && game.final.present? %>
        <% right_with_dds = game.clues_right + game.dds_right %>
        <% wrong_with_dds = game.clues_wrong + game.dds_wrong %>
        <td><%= number_to_currency(game.adjusted_game_score, precision: 0) %></td>
        <td><%= number_to_currency(game.adjusted_round_one_score, precision: 0) %></td>
        <td><%= number_to_currency(game.adjusted_round_two_score, precision: 0) %></td>
        <td><%= game.clues_right + game.clues_wrong %></td>
        <td><%= right_with_dds %></td>
        <td><%= wrong_with_dds %></td>
        <% if right_with_dds.zero? && wrong_with_dds.zero? %>
          <td>-</td>
        <% else %>
          <td><%= number_to_percentage(100 * right_with_dds.to_f / (right_with_dds + wrong_with_dds), precision: 0) %></td>
        <% end %>
        <td><%= game.dds_right %></td>
        <td><%= game.dds_wrong %></td>
        <td><%= game.final_symbol %></td>
      <% else %>
        <td colspan="6" style="text-align: center;">
          Missing data -
          <a href="#" data-toggle="modal" data-target="#bad-data-modal">
            more information here
          </a>
        </td>
      <% end %>
      <% if current_user?(game.user) %>
        <td><%= link_to 'edit', game_path(g: game.game_id) %></td>
        <td><%= link_to 'delete',
                        delete_path(game),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to ' +
                            'delete game ' +
                            game.game_id.to_s +
                            '?' } %></td>
      <% else %>
        <td class="disabled">edit</td>
        <td class="disabled">delete</td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="pagy-selector">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/stats/show.html.erb
<% if @sample %>
  <% provide(:title, 'Sample stats') %>
  <% provide(:tags, "description: A sample stats page (with the developer's real stats), to give you a taste of what the J! Scorer can do.".html_safe) %>
<% elsif @shared %>
  <% provide(:title, "Shared stats for #{@user_name}") %>
  <% provide(:tags, "description: The up-to-the-minute stats for J! Scorer user #{@user_name}.") %>
<% else %>
  <% provide(:title, 'Stats') %>
  <% provide(:tags, 'description: Your up-to-the-minute stats, broken down by game, topic, row, play type, and more.') %>
<% end %>

<div id="stats-loading-message">
  Loading stats page. One moment please.
</div>

<div id="stats-area">

  <% if false %>
  <div class="k-box">
    <p>
      <%= random_full_greeting %>
      Due to the large amount of work that would be required, the hour-long celebrity episodes are not supported. See the <%= link_to 'help page', help_path %> for more details.
      <!--
      <a class="nowrap" href="mailto:<%= ENV['SUPPORT_ADDRESS'] %>"><%= ENV['SUPPORT_ADDRESS'] %></a>.
      -->
    </p>
  </div>
  <% end %>

  <ul>
    <li><a href="#overview">Overview</a></li>
    <li><a href="#games">Games</a></li>
    <li><a href="#topics">Topics</a></li>
    <li><a href="#by-row">By row</a></li>
    <li><a href="#finals">Finals</a></li>
    <li><a href="#filters">Filters</a></li>
    <li><a href="#options">Options</a></li>
  </ul>

  <noscript>
    <div class="no-js-box text-center">
      <p>
        Note: With JavaScript enabled, this same information is in a tabbed format which is much easier to read.
      </p>
    </div>
  </noscript>

  <% user_games_count = @user.games.count %>
  <% tracked = @summary[:all][:game_count] %>

  <%= render 'overview', user_games_count: user_games_count,
                         tracked: tracked,
                         pctile: @percentile_stats %>

  <%= render 'games', user_games_count: user_games_count, tracked: tracked %>

  <%= render 'topics', stats: @stats_by_topic %>

  <%= render 'by_row', stats: @stats_by_row %>

  <%= render 'finals', stats: @final_stats %>

  <%= render 'filters', no_games: user_games_count.zero? %>

  <%= render 'options' %>

</div>