config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'help' => 'pages#help'
  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  get 'stats' => 'stats#show'
  get 'sample' => 'stats#sample'
  get 'shared/:user' => 'stats#shared', as: :shared

  get 'stats/topic/:topic' => 'stats#topic', as: :topic
  get 'sample/topic/:topic' => 'stats#sample_topic', as: :sample_topic
  get 'shared/:user/topic/:topic' => 'stats#shared_topic', as: :shared_topic

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'forgot' => 'password_resets#new'
  post 'forgot' => 'password_resets#create'
  get 'reset/:id' => 'password_resets#edit', as: :reset
  patch 'reset/:id' => 'password_resets#update'

  get 'game' => 'games#game', as: :game
  delete 'delete/:game_id' => 'games#destroy', as: :delete

  get 'backup/:backup_id/download' => 'backups#download'

  # Allow only Ajax requests to the following routes:
  constraints(->(req) { req.xhr? }) do
    get 'json/:game_id' => 'games#json', as: :json
    post 'save' => 'games#save', as: :save
    patch 'redate' => 'games#redate', as: :redate
    get 'check/:final_id' => 'games#check', as: :check

    patch 'filters' => 'users#update_user_filters'
    patch 'sharing' => 'users#update_sharing_status'

    get 'stats/games' => 'stats#games', as: :games
    get 'sample/games' => 'stats#sample_games', as: :sample_games
    get 'shared/:user/games' => 'stats#shared_games', as: :shared_games

    get 'backup' => 'backups#new'
    get 'backup/:backup_id' => 'backups#status'
    post 'restore' => 'backups#restore'
    get 'restore/:restore_id' => 'backups#restore_progress'
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <p>
  The J! Scorer is created by fans, for fans. The <i>Jeopardy!</i> game show and all elements thereof, including but not limited to copyright and trademark thereto, are the
  </p>
  <p>
  property of Jeopardy Productions, Inc. and are protected under law. This website is not affiliated with, sponsored by, or operated by Jeopardy Productions, Inc.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'J! Scorer', root_path, id: 'logo', tabindex: 32766 %>
  <nav>
    <ul class="navigation">
      <li><%= link_to 'Game', game_path, tabindex: 32767 %></li>
      <li><%= link_to 'Help', help_path, tabindex: 32767 %></li>
      <li><%= link_to 'About', about_path, tabindex: 32767 %></li>

      <% if logged_in? %>
        <li><%= link_to 'Stats', stats_path, tabindex: 32767 %></li>
        <li><%= link_to 'Log out', logout_path, method: 'delete',
                tabindex: 32767 %>
      <% else %>
        <li><%= link_to 'Log in', login_path, tabindex: 32767 %></li>
        <li><%= link_to 'Sign up', signup_path, tabindex: 32767 %></li>
      <% end %>

    </ul>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<div id="flash-messages">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= message %>
    </div>
  <% end %>
</div>

<div id="browser-warnings">
  <noscript>
    <div class="no-js-box text-center">
      <p>
        It looks like JavaScript isn't enabled in your browser. The <span class="nowrap">J! Scorer</span> relies on JavaScript to do its thing.
      </p>
      <br />
      <p>
        Feel free to take a look around. If you'd like to use the <span class="nowrap">J! Scorer</span> yourself, you'll need to either <a href="http://www.enable-javascript.com/" target="_blank" class="nowrap">enable JavaScript</a> or switch browsers.
      </p>
    </div>
  </noscript>

  <div id="old-browser-warning" class="no-js-box text-center">
    <p>
      It looks like you're using an old browser. The <span class="nowrap">J! Scorer</span> relies on CSS3 features that your browser doesn't recognize. To use the <span class="nowrap">J! Scorer</span> (and the rest of the modern web), please upgrade your browser.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= other_meta_tags(yield(:tags)) %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "name": "J! Scorer",
        "url": "https://j-scorer.com"
      }
    </script>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>">
    <%= render 'layouts/header' %>

    <%= render 'layouts/messages' %>

    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>